package com.chahd.collabproject.Enum;

public enum TypeNotification {
    COMMENTAIRE_TACHE,
    COMMENTAIRE_PROJET,
    AFFECTATION_TACHE,
    RETRAIT_TACHE,
    TACHE_BLOQUEE,
    ATTACHER_PIECEJOINTE,
    SUPPRIMER_PIECEJOINTE,
    CREER_PROJET,
    MODIFIER_PROJET,
    ECHEANCE_PROCHE,
    ECHEANCE_DEPASSEE

}
